In [14]:
import numpy as np
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [2]:
model=load_model("Engine_maintenance_keras.h5")

In [3]:
inp =[[1,1,0.45977,0.166667,0,0,0.183735,0.406802,0.309757,0,1,0.726248,0.242424,0.109755,0,0.369048,0.633262,0.205882,0.199608,0.363986,0,0.333333,0,0,0.713178,0.724662]]

In [4]:

a=np.array(inp)
a.shape
              

(1, 26)

In [5]:
model.predict(a)

array([[0.]], dtype=float32)

In [6]:
inp2=[63,11,-0.0012,-0.0003,100.0,518.67,642.18,1579.97,1407.38,14.62,21.61,554.16,2388.11,9062.53,1.30,47.36,522.04,2388.09,8138.89,8.4264,0.03,393,2388,100.00,38.98,23.3233]

In [7]:
model.predict([[inp2]])

array([[1.]], dtype=float32)

In [8]:
inp1 =[2,5,0.45977,0.166667,0,0,0.183735,0.406802,0.309757,0,1,0.726248,0.242424,0.109755,0,0.369048,0.633262,0.205882,0.199608,0.363986,0,0.333333,0,0,0.713178,0.724662]

In [9]:
model.predict([[inp1]])

array([[0.]], dtype=float32)

In [10]:
import random
inp2=[]
inp2.append(random.randint(0,100)) 
inp2.append(random.randint(0,365))
for i in range(0,24):
    inp2.append(random.uniform(0,1))

    

In [11]:
y=model.predict(np.array([inp2]))>0.9



In [15]:
y

array([[ True]])

In [17]:
sc=StandardScaler()

In [18]:
ct=MinMaxScaler()

In [19]:
inp2=[63,11,-0.0012,-0.0003,100.0,518.67,642.18,1579.97,1407.38,14.62,21.61,554.16,2388.11,9062.53,1.30,47.36,522.04,2388.09,8138.89,8.4264,0.03,393,2388,100.00,38.98,23.3233]

In [21]:
inp2=sc.fit_transform([inp2])

In [22]:
inp2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
inp3=[63,11,-0.0012,-0.0003,100.0,518.67,642.18,1579.97,1407.38,14.62,21.61,554.16,2388.11,9062.53,1.30,47.36,522.04,2388.09,8138.89,8.4264,0.03,393,2388,100.00,38.98,23.3233]

In [25]:
inp3=ct.fit_transform([inp3])

In [26]:
inp3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])